services:
  belfast-bikes:
    build: .
    container_name: belfast-bikes
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - NOTIFY_EMAIL=${NOTIFY_EMAIL}
